repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-case-conflict
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.740'
    hooks:
    -   id: mypy

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-ll, --recursive, -x, tests, --skip, B311]
        files: .py$
        

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pipenv run pylint
        language: system
        types: [python]
        exclude: ^tests/
        files: \.py$

    -   id: isort
        name: isort
        entry: pipenv run isort
        language: system
        types: [python]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

default_stages: [commit, push]
