language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
jobs:
  include:
    # command to run tests
    - stage: "Code Quality Assurance"
      script: make ci-bundle
    - state: "Tags Version"
      script: 
        - make bump
        - git push origin --tags
        