language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
services:
- docker
jobs:
  include:
  - stage: Code Quality Assurance
    name: "Code Quality Assurance"
    script: 
    - make ci-bundle
  - stage: Tags Version
    name: "Tags Version"
    script:
    - make bump
    - git remote set-url origin https://grandq33769:$GH_TOKEN@github.com/grandq33769/data-simulator.git
    - git push origin --tags
  - stage: Build Docker Image 
    name: "Build Docker Image"
    script: 
    - make docker-build name=$TRAVIS_REPO_SLUG
    - docker login -u="$DOCKER_AC" -p="$DOCKER_PW"
    - make docker-deploy name=$TRAVIS_REPO_SLUG tag=latest
env:
  global:
    secure: f6MOKM8OeLmqobfd99D/2ytdLyv8StxgCfUbp1HghiQp0Z4fYl/ZjZt1XU7vSoTe90vaeiT122EPS16x+8omE+uUjnRrKmZLAIyM4lPmAyu/3aQm+2Zmg/K6QY+LRSx1rFLkU1mZJ7CZ77yC/DdUCJnxeFJ+3lkP58A51N94aSYlulyFRWy9u5w41Pc87JZ7irCtFfT/sUOukalUsSNISbE+Q0YOIPCC4ebXf5P3DZ4LJeWs1iT/h+xUUSzjfStfZn+hozkpNK5HA72u4Mpn2Douf65Zmo7A6t4cpVVpJstkR3ybVJbMUYS31i3eXBuR70CjiZjtrhtblr7ZBQ9s9KDP9POLFX7mUFTgveoMgEf5OMr6Qq1jVLRS+9Gd0P5zYg5Go15kns0eTJkLwQiZZeyExt7EimOl5udd+2YURumvq8b1f4NU4uUT9caQUlY2fF5lWb+zvNfAsfcQibYXGMQ2yCKPbJ/k53sNGjQEtHpIQiiXPNeH2LYunODrU/o1sJkgtA/LERJ0xOAbB+aPrFz2TAX1UKwdvLPOI9rhrTwSXgFk+Yi2Ugwud97THrUvkfgQGZBAXzVGKao3XRF9Hz3M3/wt9RjuzoESFZuQiDgO1FbzXSrirwMpXhOGkr9147ehVZ76DMm5f8YoNZ7zrCiWTqOhdeL+w6CUGMlGZNw=
