---
version: '3'

services:

  data-simulator:
    build: .
    image: grandq33769/data-simulator:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./src/configs:/src/configs
